name: .NET CI

env:
  registryName: aqzjinqxvt56kmpnpreg.azurecr.io
  repositoryName: techexcel/dotnetcoreapp
  dockerFolderPath: ./src/Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}

on:
  push:
    branches: [ "main" ]
    paths: src/Application/**
  pull_request:
    branches: [ "main" ]
    paths: src/Application/**
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
      
  dockerBuildPush:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        logout: true
    - name: Docker Build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker Push
      run: docker push $registryName/$repositoryName:$tag

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: dockerBuildPush
    environment:
      name: dev
      url: https://aqzjinqxvt56kmpnpreg-dev.azurewebsites.net/
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'aqzjinqxvt56kmpnpreg-dev'
          images: aqzjinqxvt56kmpnpreg.azurecr.io/techexcel/dotnetcoreapp:${{github.run_number}}

  deploy-to-test:
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    environment:
      name: test
      url: https://aqzjinqxvt56kmpnpreg-test.azurewebsites.net/
    steps:
    - uses: actions/checkout@v3
    - name: 'Login via Azure CLI'
      uses: azure/login@v2.1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: '{your_prefix}-test'
        images: aqzjinqxvt56kmpnpreg.azurecr.io/techexcel/dotnetcoreapp:${{github.run_number}}

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: deploy-to-test
    environment:
      name: prod
      url: https://aqzjinqxvt56kmpnpreg-prod.azurewebsites.net/
    steps:
    - uses: actions/checkout@v3
    - name: 'Login via Azure CLI'
      uses: azure/login@v2.1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: '{your_prefix}-prod'
        images: aqzjinqxvt56kmpnpreg.azurecr.io/techexcel/dotnetcoreapp:${{github.run_number}}
        
