name: First Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]
        
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo phrase for job1
        run: echo "This is job1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: "Ready for prod--ship it!"
          color: "magenta"